name: Build TCL-IR
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y gcc cmake tcl-dev

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
